# Generated by Django 3.2.15 on 2022-09-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='Введите название книги', max_length=250, verbose_name='Название книги'),
        ),
    ]
